services:
  db:
    image: postgres:17.0-bookworm
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_USER=admin
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
  api:
    image: au79-api-img
    build:
      context: .
      args:
        BUN_VERSION: 1.1.32
        NODE_VERSION: 23.0.0
        CI: true # Simulate production build
    environment:
      PORT: 7979
    ports:
      - 7979:7979
